### ISSUE TITLE
After run createInjectDebugDexes or createInjectReleaseDexes, no dex file is created

### ISSUE THREAD

**Issue by reallychenchi** [artyomd/Injector#49]
Hello, after run createInjectDebugDexes or createInjectReleaseDexes, the gradle reports no error, but dex file is not found either.
What's the possible problem please?

**Comment by artyomd** [comment]
Hi @reallychenchi 

Please send an example project which is reproducing your issue

**Comment by artyomd** [comment]
Hi @reallychenchi 

Please send an example project which is reproducing your issue

**Comment by wavaya** [comment]
I also meet it 
 

https://github.com/wavaya/inject_test

**Comment by artyomd** [comment]
@wavaya  your repo URL is invalid, pls check that it is accessible to everyone.

**Comment by wavaya** [comment]
Hi artyomd,
      I'm sorry ! I changed.
      Thank you!




------------------ 原始邮件 ------------------
发件人: "Artyom"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 凌晨1:20
收件人: "artyomd/Injector"<Injector@noreply.github.com>;
抄送: "Danny"<48366939@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [artyomd/Injector] After run createInjectDebugDexes orcreateInjectReleaseDexes, no dex file is created (#49)




@wavaya  your repo URL is invalid, pls check that it is accessible to everyone.

**Comment by artyomd** [comment]
@wavaya, first of all, you are injecting Lottie lib, but in inject config you are declaring a dex file with a completely different package name rather than Lottie's package name. With this config, u should get an inject.dex.zip file that contains only Lottie's class. **Injectconfig is just a configuration** what to do with injected dependencies of dividing them into smaller dexes`. To be able to divide the injected dependencies into files, first of all, you must **inject them**.

**Comment by wavaya** [comment]
can u help me make mylib to dexs?
do not inject lotties

**Comment by artyomd** [comment]
@wavaya pls instead of asking help formulate your question correctly so you can understand how this lib is working. I am the creator of this project and I know how is everything working, but I don't know which part of this is not clear to others. So by asking questions besides that, it helps you to understand how this lib works, it helps other people who are struggling with the same issue.

**Comment by yagnasrinath** [comment]
@artyomd Can I get a zipped dex file without injecting any additional libraries? It doesn't seem to generate a zip, without any inject, but with an injectConfig block and enabled set to true. Am I missing something here?

**Comment by artyomd** [comment]
@yagnasrinath no you cannot, the whole idea of this project is to generate dex files for your project dependencies, if you are not specifying any dependency to be injected there is no need to create a dex file

**Comment by yagnasrinath** [comment]
@artyomd thanks for clarifying. Another question I have is what happens to jni libs. I don't see them as part of the zip.

**Comment by artyomd** [comment]
@yagnasrinath that zip file is just a zipped dex. Why are you expecting it to contain so files? This project main goal is to provide a way to download and load aar library at runtime. Native libraries are self-contained and you can always separate them and download at runtime and load with System.load. The rest is a jar file and resources. This project is addressing resources and the jar file.

**Comment by yagnasrinath** [comment]
I was just curious about merge jni function.

**Comment by artyomd** [comment]
This issue has not been updated for about 17 days. I am closing this issue. If you are still struggling with problems connected to Injector pls create a separate issue with a concrete question.
