### ISSUE TITLE
Doing injector from lib folder

### ISSUE THREAD

**Issue by nfscarbon2010** [artyomd/Injector#70]
Hi it's just a query, not a bug report 

In the example you inject inject 'com.airbnb.android:lottie:3.0.6' . But I have aar file which is in lib folder, is there is any way to inject aar from lib folder.

**Comment by artyomd** [comment]
Hi, thanks for your question. The design of this project does not mention the location of the dependency so, yes you should be able to inject from the libs folder. I have never tested that functionality and I have found out that there is a bug while injecting the local aar. So currently there is no way to do that, but it will be fixed in the next release, Thank you

**Comment by nfscarbon2010** [comment]
Thanks, artyomd for your response.
 
Hopefully, you will update the library soon. It will be great if you mention the example of the same when you fix this bug.

**Comment by artyomd** [comment]
@nfscarbon2010 0.4.1 version is released. Pls, check that version and if issues occur, pls create another issue. I am closing this issue.
